# Generated by Django 5.2.12 on 2026-03-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_categoria_proveedor_insumo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='costo_unidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='costo_aprox',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
