# Generated by Django 5.2.12 on 2026-03-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_insumo_costo_unidad_registrodiario_costo_aprox'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='idRegistro',
            field=models.IntegerField(default=0),
        ),
    ]
