# Generated by Django 5.2.12 on 2026-03-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_registrodiario_idregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='cantidad_a_comprar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='costo_unidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='estado',
            field=models.CharField(default='OK', max_length=20),
        ),
    ]
