# Generated by Django 5.2.12 on 2026-03-19 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_registrodiario_cantidad_a_comprar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='proveedor_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_secundarios', to='inventory.proveedor'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_principales', to='inventory.proveedor'),
        ),
    ]
